name: Windows Test
on: push
jobs:
  test:
    runs-on: windows-2016
    env:
      GOPATH: ${{ github.workspace }}
      GOVERSION: 1.15.13
      MSYS_ROOT: C:\msys64
      DD_AGENT_BUILD_FOLDER: src/github.com/DataDog/datadog-agent
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: DataDog/datadog-agent
          path: ${{ env.DD_AGENT_BUILD_FOLDER }}
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Golang
        uses: paulcacheux/setup-go@bba6fe1d5876b1bc23cf834e6c825047156461ec
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Setup ddagentuser
        run: |
          $Password = ConvertTo-SecureString "dummyPW_:-gch6Rejae9" -AsPlainText -Force
          New-LocalUser -Name "ddagentuser" -Description "Test user for the secrets feature on windows." -Password $Password
      - name: Setup PATH
        run: |
          echo "$env:GITHUB_WORKSPACE\$env:DD_AGENT_BUILD_FOLDER\dev\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:GOPATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:MSYS_ROOT\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:MSYS_ROOT\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install tools and dependencies
        working-directory: ${{ env.DD_AGENT_BUILD_FOLDER }}
        run: |
          pip install -r requirements.txt
          inv -e install-tools
          inv -e deps

      - name: Build and Test
        working-directory: ${{ env.DD_AGENT_BUILD_FOLDER }}
        run: |
          inv -e rtloader.make --install-prefix=$env:DD_AGENT_BUILD_FOLDER\dev --cmake-options="-G \"MSYS Makefiles\""
          inv -e rtloader.install
          inv -e rtloader.format --raise-if-changed
          inv -e rtloader.test
          inv -e test --python-runtimes 3 --coverage --profile --fail-on-fmt
